//searchProfile
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

//requestProfile
export const REQUEST_PROFILE_PENDING = 'REQUEST_PROFILE_PENDING';
export const REQUEST_PROFILE_SUCCESS = 'REQUEST_PROFILE_SUCCESS';
export const REQUEST_PROFILE_FAILED = 'REQUEST_PROFILE_FAILED';